# Generated by Django 5.0.1 on 2024-02-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_challenge_remove_user_id_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="id",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="num_completed",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="username",
        ),
        migrations.AddField(
            model_name="challenge",
            name="title",
            field=models.CharField(
                default="", max_length=70, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="UserChallenges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.user"
                    ),
                ),
            ],
        ),
    ]
