# Generated by Django 5.0.1 on 2024-02-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_remove_challenge_id_remove_challenge_num_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengesAssigned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateField()),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.challenge",
                    ),
                ),
            ],
        ),
    ]
