# Generated by Django 5.0.1 on 2024-02-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_challengesassigned_dailychallenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenges',
            name='daily_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dailychallenge'),
        ),
    ]
