# Generated by Django 5.0.1 on 2024-03-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_userchallenges_user_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchallenges",
            name="user_lat",
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 13, 51, 7, 706584, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 13, 51, 7, 706794, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
