# Generated by Django 5.0.1 on 2024-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_userchallenges_daily_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
