# Generated by Django 5.0.1 on 2024-02-24 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_alter_challenge_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailychallenge",
            name="date_assigned",
        ),
        migrations.RemoveField(
            model_name="userchallenges",
            name="daily_challenge",
        ),
        migrations.AddField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 24, 19, 54, 3, 159722)
            ),
        ),
        migrations.AddField(
            model_name="userchallenges",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
