# Generated by Django 5.0.1 on 2024-03-18 13:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_userchallenges_user_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=25)),
                ("cost", models.PositiveIntegerField()),
                ("max_quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 13, 51, 52, 986624, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 13, 51, 52, 986823, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchased",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            3,
                            18,
                            13,
                            51,
                            52,
                            986168,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("item_number", models.PositiveIntegerField()),
                ("row_position", models.IntegerField()),
                ("col_position", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.villageshop",
                    ),
                ),
            ],
        ),
    ]
