# Generated by Django 5.0.1 on 2024-03-18 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_villageshop_alter_dailychallenge_assigned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="village",
            name="col_position",
        ),
        migrations.RemoveField(
            model_name="village",
            name="row_position",
        ),
        migrations.AddField(
            model_name="village",
            name="position",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="villageshop",
            name="image_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 0, 490897, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 0, 491090, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="purchased",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 0, 490473, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
