# Generated by Django 5.0.1 on 2024-02-24 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_remove_dailychallenge_date_assigned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 24, 19, 55, 35, 761485)
            ),
        ),
    ]
