# Generated by Django 5.0.1 on 2024-03-18 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_villageshop_alter_dailychallenge_assigned_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="village",
            old_name="item_number",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="village",
            name="col_position",
        ),
        migrations.RemoveField(
            model_name="village",
            name="row_position",
        ),
        migrations.AddField(
            model_name="customuser",
            name="coins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="villageshop",
            name="image_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 22, 16, 36, 4207, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 22, 16, 36, 4396, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="purchased",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 22, 16, 36, 3794, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
