# Generated by Django 5.0.1 on 2024-02-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_dailychallenge_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 24, 19, 57, 38, 91704, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
