# Generated by Django 5.0.1 on 2024-03-18 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_remove_village_col_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="village",
            name="item_number",
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 51, 318239, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 51, 318439, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="purchased",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 16, 20, 51, 317810, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
