# Generated by Django 5.0.1 on 2024-02-24 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_dailychallenge_assigned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="points",
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 24, 20, 3, 48, 334804, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
