# Generated by Django 5.0.1 on 2024-02-24 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_remove_customuser_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 24, 20, 8, 37, 760494, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
