# Generated by Django 5.0.1 on 2024-03-18 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_dailychallenge_assigned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 19, 21, 48, 541079, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 19, 21, 48, 541280, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="purchased",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 19, 21, 48, 540641, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
