# Generated by Django 5.0.1 on 2024-03-18 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_alter_dailychallenge_assigned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="coins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="assigned",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 20, 14, 39, 59938, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userchallenges",
            name="submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 20, 14, 39, 60126, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="purchased",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 18, 20, 14, 39, 59535, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
