# Generated by Django 4.2.9 on 2024-03-20 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_customuser_score_alter_dailychallenge_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='assigned',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 17, 22, 504532, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='userchallenges',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 17, 22, 504532, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='village',
            name='purchased',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 11, 17, 22, 504532, tzinfo=datetime.timezone.utc)),
        ),
    ]
