# Generated by Django 4.2.9 on 2024-02-26 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_dailychallenge_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='assigned',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 18, 36, 50, 249450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userchallenges',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 18, 36, 50, 250450, tzinfo=datetime.timezone.utc)),
        ),
    ]
